services:
  emqx:
    image: emqx:5.8.8
    container_name: emqx
    ports:
      - "1883:1883"     # MQTT TCP (ESP32 / clientes MQTT)
      - "8083:8083"     # MQTT over WebSocket
      - "18083:18083"   # Dashboard EMQX
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    restart: unless-stopped

  mqttx-web:
    image: emqx/mqttx-web:latest
    container_name: mqttx-web
    ports:
      - "8080:80"       # MQTTX Web no navegador
    restart: unless-stopped

volumes:
  nats-js:

